### ISSUE TITLE
Optimization fallback()  function

### ISSUE THREAD

**Issue by YingQm** [mudgen/diamond-1-hardhat#1]
In Diamond.sol [fallback function ](https://github.com/mudgen/diamond-1-hardhat/blob/main/contracts/Diamond.sol#L33)
```
 LibDiamond.DiamondStorage storage ds;
        bytes32 position = LibDiamond.DIAMOND_STORAGE_POSITION;
        // get diamond storage
        assembly {
            ds.slot := position
        }
```
why not use `LibDiamond.DiamondStorage storage ds = LibDiamond.diamondStorage();`?

**Comment by mudgen** [comment]
Because using `LibDiamond.diamondStorage()` costs a bit more gas and the fallback is very frequently called.
