### ISSUE TITLE
Comments are flagged as invalid doc tags

### ISSUE THREAD

**Issue by pakim249CAL** [mudgen/diamond-1-hardhat#12]
Importing some of these contracts results in an invalid doc tag solidity compiler error when using this repo as a submodule, importing them, and compiling the contracts with foundry.
![image](https://github.com/mudgen/diamond-1-hardhat/assets/70043880/2e34bc57-c8cc-4747-b7b3-2fe97874d31f)

**Comment by mudgen** [comment]
I fixed it, thanks!

**Comment by mudgen** [comment]
Is this still a problem?   I am not getting compilation errors with Solidity 0.8.24

**Comment by pakim249CAL** [comment]
Yes, the latest commit fixed it. Thanks!
