### ISSUE TITLE
Consider removing enforcing contract code for init

### ISSUE THREAD

**Issue by pakim249CAL** [mudgen/diamond-1-hardhat#13]
[This ](https://github.com/mudgen/diamond-1-hardhat/blob/3da037b378195b4108b977cf2014600eeddbf67d/contracts/libraries/LibDiamond.sol#L196)check IMO provides no security benefits, but causes some of my deployments to fail when submitted in a batch through foundry script.

**Comment by mudgen** [comment]
Understood, and I am interested in a solution that resolves this.

Contract existence check has a couple of benefits:

1. It prevents people from making the mistake of adding a function to a diamond from a facet that does not exist.
2. It prevents people from thinking that function calls are successful when they are not.  Because delegatecalls to non-existent facets do not revert in some cases.

**Comment by mudgen** [comment]
> [This ](https://github.com/mudgen/diamond-1-hardhat/blob/3da037b378195b4108b977cf2014600eeddbf67d/contracts/libraries/LibDiamond.sol#L196)check IMO provides no security benefits, but causes some of my deployments to fail when submitted in a batch through foundry script.

Is there anyway to make your deployment deploy the facets before deploying the diamond?  Can you enforce an order of deployment/actions?

**Comment by pakim249CAL** [comment]
Foundry's script utility does enforce the order of txs. The problem is that even with correct ordering, the contract existence check can still fail. My particular case involves submitting a lot of txs to tenderly in rapid succession, and the RPC does not update the state quickly enough to recognize that a facet was deployed unless I use slow mode. It's also happened to me in the past when trying to create diamonds with foundry on mainnet. Debugging this was kind of a nightmare, and I imagine that others may experience that same pain for no good reason.

IMO a standard implementation should not do these kinds of checks. It should be the responsibility of the diamond owner to correctly configure the diamond, and there should be no restrictions on the diamond owner. With the current state, I am tempted to override a lot of the diamond library because restrictions like these make it difficult to work with.

**Comment by mudgen** [comment]
> Foundry's script utility does enforce the order of txs. The problem is that even with correct ordering, the contract existence check can still fail. My particular case involves submitting a lot of txs to tenderly in rapid succession, and the RPC does not update the state quickly enough to recognize that a facet was deployed unless I use slow mode. It's also happened to me in the past when trying to create diamonds with foundry on mainnet. Debugging this was kind of a nightmare, and I imagine that others may experience that same pain for no good reason.

Interesting!

> IMO a standard implementation should not do these kinds of checks. It should be the responsibility of the diamond owner to correctly configure the diamond, and there should be no restrictions on the diamond owner. With the current state, I am tempted to override a lot of the diamond library because restrictions like these make it difficult to work with.

It is not just a standard implementation it is a reference implementation -- that just means it is an example that is guaranteed by the author of the EIP-2535 standard  to follow the standard.  Any implementation that complies with the [EIP-2535 standard](https://eips.ethereum.org/EIPS/eip-2535) is a standard implementation.

I do not expect or want everyone to use the reference implementations.  The standard was designed to be very flexible but still ensure interoperability between implementations and tooling. The standard is flexible so people can invent new kinds of solutions and do a broad variety of different things.

The EIP-2535 standard certainly does not require a contract existence check. I very much recommend changing the reference implementation to suit your needs (while maintaining EIP2535 compliance) or making your own implementation that complies with the standard. An article that focuses on what is required by the standard is here: https://eip2535diamonds.substack.com/p/compliance-with-eip-2535-diamonds

**Comment by pakim249CAL** [comment]
Got it. Makes sense. I think I was motivated by the fact that there are not a lot of options for plug and play diamond implementations that fit my particular needs, and I don't want to need an audit on the diamond contract itself. But this is definitely not a problem with your repo if it's just a reference. Thanks for your attention to this issue.
