### ISSUE TITLE
How to upgrade a Library

### ISSUE THREAD

**Issue by coinlordd** [mudgen/diamond-1-hardhat#4]
Considering supportive Libraries aren't deployed on their own I wonder how the DiamondCut can broadcast an updated library to all facets. Would be great if this was added to the examples in the /test/ directory. Thank you!

**Comment by mudgen** [comment]
Yes, thanks.  To answer your question, an updated library can be updated to all facets in a diamond by replacing all external functions in the diamond that use the old library with new external functions that use the updated library.

**Comment by mudgen** [comment]
I added your question and the answer to the article here: https://eip2535diamonds.substack.com/p/common-diamond-errors
